-- =========================================
-- XENO SUPABASE SCHEMA (Historical Reference)
-- =========================================
-- This schema is no longer required. Xeno now runs fully local:
-- tour data in localStorage, media files in /media/ folder.
--
-- Keep this file if you ever want to self-host Supabase again.
-- Otherwise it can be deleted.
--
-- Tables: tours, albums, media
-- Storage bucket: xeno-media
-- See Git history for the full DDL.
-- =========================================
